---
default_stages: [commit]

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # We re-set the `stages` setting because pre-commit-hooks over-rides it
      # otherwise.
      # See https://github.com/pre-commit/pre-commit-hooks/issues/515
      - id: end-of-file-fixer
        stages: [commit]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        stages: [commit]
      - id: check-added-large-files
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: local
    hooks:
      - id: pre-commit update
        name: run all tests
        stages: [push]
        language: system
        entry: poetry run pytest --full-trace
        pass_filenames: false

      - id: pyproject.toml
        name: validate pyproject.toml
        language: system
        entry: poetry check
        files: 'pyproject\.toml'
        pass_filenames: false

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: poetry run flake8
        types: [python]
