---
name: pipeline
on:
  push:
    branches:
      - main

jobs:
  lint_and_test_code:
    steps:
      - uses: actions/checkout@v3.5.0

      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.11.4

      - name: Install build & test dependencies
        run: |-
          pip3 install --disable-pip-version-check --progress-bar off poetry pre-commit
          apt-get update && apt-get install shellcheck && apt-get install direnv

      - name: Build & install
        run: poetry build && poetry install

      - name: Run pre-commit hooks on all files
        run: poetry run pre-commit run --all-files --show-diff-on-failure

      - name: Run tests
        run: |-
          direnv allow
          poetry run pytest --full-trace

      - uses: actions/upload-artifact@v3.1.1
        with:
          path: dist
